version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/tmp
    environment:
      - CHROME_PATH=/usr/bin/chromium